language: php
php:
  - '7.1'

install:
  - composer self-update
  - make install
  - ActiveRecord::Base.establish_connection :adapter => 'sqlite3',
                                            :database => ':memory:'

script: make lint test
